version: 0.2

phases:
  install:
    commands:
    - echo Entered the install phase...
  pre_build:
    commands:
    - echo Entered the pre_build phase...
  build:
    commands:
    - echo Entered the build phase...
    - echo Build started on `date`
    - sudo apt-get update
    - sudo apt-get install -y rsync
    - echo Building Backend
    - npm install
    - mkdir -p build
    - rsync -av --exclude=node_modules/* ./ build
    - rsync -av .ebextensions build
  post_build:
    commands:
    - echo Entered the post_build phase...
    - echo Build completed on `date`
artifacts:
  files:
  - '**/*'
  base-directory: build
  discard-paths: no
cache:
  paths:
  - 'node_modules/**/*'
